### ISSUE TITLE
Update the page more regularly

### ISSUE THREAD

**Issue by Ads20000** [cnguy/onetricks.net#14]
[Risti hit Masters with Garen 14 hours ago](http://na.op.gg/summoner/userName=riste) but onetricks.net doesn't seem to have updated yet, is this part of the algorithm or does the page not update fast enough (how often _does_ it update)?

**Comment by cnguy** [comment]
Forgot to close this issue in the past! It's technically open, but we can use https://github.com/cnguy/onetricks.net/issues/18 for discussion
